import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define new fonts for Arabic and sans-serif
const arabicFont = localFont({
  src: "./fonts/Amiri-Regular.ttf", // Assuming Amiri font is used for Arabic content
  variable: "--font-arabic",
  weight: "400",
});

const sansSerifFont = localFont({
  src: "./fonts/Inter-VariableFont.ttf", // Assuming Inter is the new sans-serif font
  variable: "--font-sans-serif",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "MG-page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      {" "}
      {/* Arabic RTL and language support */}
      <body
        className={`${arabicFont.variable} ${sansSerifFont.variable} antialiased bg-gradient-to-b from-blue-100 to-blue-300 text-gray-900`}
      >
        {children}
      </body>
    </html>
  );
}
